version: '3'

services:
  frontend:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/mnt/golstatic
    ports:
      - "80:80"
    networks:
      golnet:
        ipv4_address: 172.0.0.10
  game:
    build:
      context: .
      dockerfile: ./Dockerfile-webapp
    networks:
      golnet:
        ipv4_address: 172.0.0.20

networks:
  golnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
