[package]
name = "conway"
version = "0.1.0"
authors = ["treyzania <treyzania@gmail.com>"]

[dependencies]
actix = "0.5"
futures = "0.1"
clap = "2.27.*"

[[bin]]
name = "conwayserver"
path = "src/main.rs"

[lib]
path = "src/lib.rs"
